### ISSUE TITLE
Opt-in, or at least opt-out, of injections?

### ISSUE THREAD

**Issue by bendemboski** [salsify/ember-debug-logger#14]
I installed `ember-milestones` in my application, and suddenly started failing on startup with this very cryptic stack trace:

```
router.js:929 Error while processing route: hub.index Cannot set read-only property 'debug' on object: <groening@service:app-config::ember286> Error: Cannot set read-only property 'debug' on object: <groening@service:app-config::ember286>
    at new EmberError (http://tp.localhost:5200/assets/vendor.js:16991:31)
    at AliasedProperty_readOnlySet [as set] (http://tp.localhost:5200/assets/vendor.js:44875:15)
    at Class.CoreObject (http://tp.localhost:5200/assets/vendor.js:54194:26)
    at Class.EmberObject (http://tp.localhost:5200/assets/vendor.js:54598:75)
    at Class (http://tp.localhost:5200/assets/vendor.js:54277:72)
    at new Class (http://tp.localhost:5200/assets/vendor.js:54277:72)
    at Function.create (http://tp.localhost:5200/assets/vendor.js:54290:16)
    at FactoryManager.create (http://tp.localhost:5200/assets/vendor.js:32050:39)
    at instantiateFactory (http://tp.localhost:5200/assets/vendor.js:31895:69)
    at _lookup (http://tp.localhost:5200/assets/vendor.js:31842:16)
    at Container.lookup (http://tp.localhost:5200/assets/vendor.js:31741:20)
    at Class.lookup (http://tp.localhost:5200/assets/vendor.js:52725:33)
    at Class.injectedPropertyGet (http://tp.localhost:5200/assets/vendor.js:46125:22)
    at InjectedProperty.get (http://tp.localhost:5200/assets/vendor.js:44604:36)
    at _get (http://tp.localhost:5200/assets/vendor.js:43445:35)
    at Class.get (http://tp.localhost:5200/assets/vendor.js:52917:34)
    at Class.<anonymous> (http://tp.localhost:5200/assets/groening.js:16676:28)
    at Generator.next (<anonymous>)
    at Class._resumeGenerator (http://tp.localhost:5200/assets/vendor.js:329002:46)
    at Class._handleResolvedContinueValue (http://tp.localhost:5200/assets/vendor.js:329157:12)
```

This is my application route's `beforeModel` hook instantiating a services that has a property called `debug` that is a `readOnly` computed property. This stack trace is the service failing to instantiate because the injection in `ember-debug-logger`'s instance initializer is trying to set the read-only `debug` property. It took some debugging through the guts of the container before finding a clue pointing back to `ember-debug-logger`, which I didn't even know I had installed because it was only included as a dependency of `ember-milestones` (which doesn't even need the initializer -- it just uses the module import functionality).

It doesn't seem too unlikely for some route, controller, component, or service in an application (or in any addon that the application uses) to have a property called `debug`, and with the current setup this addon will either clobber that property, or throw an exception similar to the one I encountered. Especially if this addon is going to be consumed from other addons, this behavior seems extra risky, and extra hard to figure out what happened when it does cause problems.

My preference would be to have the initializer's behavior be opt-in, probably via `config/environment.js`. It can easily be injected where needed (as shown in the adapter example in the readme), so the initializer isn't necessary, but could still be maintained as opt-in for people that want it injected everywhere.

If opt-in is not acceptable, it should at least be opt-out-able. Currently I think the only way to opt out is to implement an initializer called `debug-logger` to override the one exported into the app namespace by this addon and prevent it from running. But I very much think the injections should be opt-in since they are so invasive and potentially harmful.

**Comment by dfreeman** [comment]
Sorry you ran into that, @bendemboski! That injection dates from wayyy back when addons dropping random nonsense on your objects was more common and the injection helpers (e.g. `foo: service()`) didn't even exist yet, but it was never a great pattern and certainly hasn't aged well.

Honestly I think the path forward here is just to drop the injection entirely and cut a 2.0 release. Once that's done I'll also publish a new `ember-milestones` version as well.

**Comment by bendemboski** [comment]
Cool! I didn't want to hate on the initializer-injections _too_ much because maybe somebody likes them...but I hate initializer-injections 😄
